DROP EVENT IF EXISTS `ev_matches_slop`;
DELIMITER $$
CREATE EVENT `ev_matches_slop` ON SCHEDULE EVERY 1 DAY STARTS '2014-02-04 05:00:00' ON COMPLETION NOT PRESERVE ENABLE DO CALL sp_set_message_temp_match_slop()
$$ DELIMITER ;